AlexPanic/practicum-android-diploma

.gitignore, app/src/main/java/ru/practicum/android/diploma/creator/Debounce.kt, app/src/main/java/ru/practicum/android/diploma/creator/Resource.kt, app/src/main/java/ru/practicum/android/diploma/creator/SingleLiveEvent.kt
для дебаунса, Response для сетевых ответов и SingleLiveEvent который использовался для показа тоста из модели
=> Добавил вспомогательные классы

app/src/main/AndroidManifest.xml
1. Разрешения (информация о состоянии сети и право на использование сети)
2. Запрет на смену ориентации телефона
3. Контроль поведения клавиатуры на экране
=> Добавлено:

app/src/main/java/ru/practicum/android/diploma/data/network/HhApiService.kt, app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt, app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/util/App.kt, app/src/main/res/values/strings.xml
Добавил dataModule и внедрил koin через App
=> Начальная настройка DI через koin

app/src/main/java/ru/practicum/android/diploma/favorites/presentation/view/FavoriteFragment.kt, app/src/main/java/ru/practicum/android/diploma/root/ui/RootActivity.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/team/ui/TeamFragment.kt, app/src/main/res/layout/activity_root.xml, app/src/main/res/layout/fragment_favorite.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/fragment_team.xml, app/src/main/res/navigation/nav_graph.xml
1. Сделал граф навигации
2. Основные экраны
=> Сделал первичную навигацию с заглушками.

app/src/main/AndroidManifest.xml, app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt, app/src/main/java/ru/practicum/android/diploma/search/data/api/VacanciesRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/data/dto/Response.kt, app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancyDto.kt, app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancySearchRequest.kt, app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancySearchResponse.kt, app/src/main/java/ru/practicum/android/diploma/search/data/network/HhApiService.kt, app/src/main/java/ru/practicum/android/diploma/search/data/network/RetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/api/VacanciesInteractor.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/api/VacanciesRepository.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/impl/VacanciesInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/models/SearchState.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/models/SearchViewModel.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/util/App.kt, app/src/main/java/ru/practicum/android/diploma/vacancy_details/presentation/models/Vacancy.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetail/presentation/models/Vacancy.kt, app/src/main/res/layout/fragment_search.xml
Только чтобы проверить API и накинуть DI, модель и интерактор.
В модель Vacancy поля буду добавлять отдельными ветками
=> Базовая структура для сетевых запросов к поиску

app/src/main/java/ru/practicum/android/diploma/search/data/api/VacanciesRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancySearchRequest.kt, app/src/main/java/ru/practicum/android/diploma/search/data/network/HhApiService.kt, app/src/main/java/ru/practicum/android/diploma/search/data/network/RetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/api/VacanciesInteractor.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/api/VacanciesRepository.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/impl/VacanciesInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/models/SearchViewModel.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt
Установил QueryMap в API, для теста пробросил от модели до API параметры Номер страницы и Кол-во элементов на странице
=> Установил QueryMap в API, добавил отправку page, per_page на будущее

app/src/main/java/ru/practicum/android/diploma/root/ui/RootActivity.kt, app/src/main/res/layout/activity_root.xml, app/src/main/res/menu/menu_bottom_navigation.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
Сделал структура bottomNav 
Настроил переходы.
=> Создал BottomNavigationView

app/src/main/java/ru/practicum/android/diploma/filters/ui/FilterFragment.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetail/presentation/view/VacansyDetailsFragment.kt, app/src/main/res/layout/fragment_filters.xml, app/src/main/res/layout/fragment_vacansy_details.xml, app/src/main/res/navigation/nav_graph.xml
Добавил экраны-заглушки для экранов Описание вакансии и Фильтры
=> Новые графы

app/build.gradle.kts, app/src/main/java/ru/practicum/android/diploma/favorites/presentation/view/FavoriteFragment.kt, app/src/main/java/ru/practicum/android/diploma/root/ui/RootActivity.kt, app/src/main/java/ru/practicum/android/diploma/search/data/HhQueryOptions.kt, app/src/main/java/ru/practicum/android/diploma/search/data/network/RetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/team/ui/TeamFragment.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/presentation/view/VacancyDetailsFragment.kt
- viewBinding во фрагментах
- против утечки памяти во фрагментах зануляем _binding на DestroyView
- в RootActivity сделаем binding через lateinit, чтобы не занулять
- Вернул как было - minSdk берется автоматом из libs.versions.toml
- Удалил .gitkeep из непустых папок
- удалил лишний код (пример)
- Вынес ключи запроса к API в enum class
=> Исправления по ПР первой итерации

app/src/main/java/ru/practicum/android/diploma/common/domain/EmployerInfo.kt, app/src/main/java/ru/practicum/android/diploma/common/domain/NameInfo.kt, app/src/main/java/ru/practicum/android/diploma/common/domain/SalaryInfo.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/models/VacancySearchResultItem.kt
дата класc NameInfo - общий для Details и Filter (справочники)
=> Общие дата-классы вынесены в common, добавлен класc NameInfo

app/src/main/res/drawable/arrow_back_24px.xml, app/src/main/res/drawable/background_light_gray_rounded.xml, app/src/main/res/layout/fragment_vacancy_details.xml
для того, чтобы можно было пробрасявать данные на экран избранное
=> Сделал первичный макет Описния вакансии

app/src/main/res/layout/fragment_favorite.xml, app/src/main/res/layout/item_favorite_view.xml, app/src/main/res/layout/item_vacancy_view.xml, app/src/main/res/values/strings.xml
Добавление верстки экрана fragment_favorite, item_favorite_view
=> Верстка для экрана "Избранное"

app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt, app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/favorites/data/converters/VacancyDbConverter.kt, app/src/main/java/ru/practicum/android/diploma/favorites/data/db/VacancyDao.kt, app/src/main/java/ru/practicum/android/diploma/favorites/data/db/VacancyDatabase.kt, app/src/main/java/ru/practicum/android/diploma/favorites/data/db/VacancyEntity.kt, app/src/main/java/ru/practicum/android/diploma/favorites/data/impl/FavouriteVacancyRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/favorites/domain/db/FavouriteVacancyInteractor.kt, app/src/main/java/ru/practicum/android/diploma/favorites/domain/db/FavouriteVacancyRepository.kt, app/src/main/java/ru/practicum/android/diploma/favorites/domain/impl/FavouriteVacancyInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/favorites/domain/models/FavouriteVacanciesModel.kt
=> task-36: created database

app/src/main/java/ru/practicum/android/diploma/search/data/network/RetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/search/data/repo/SearchRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/models/Currency.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/VacancySearchViewHolder.kt, app/src/main/java/ru/practicum/android/diploma/util/Formatter.kt, app/src/main/res/layout/item_favorite_view.xml, app/src/main/res/values/strings.xml
1. Иконка компании на 240 выглядит в эмуляторе гораздо качественнее чем 90
2. разбил функцию, чтобы детект не ругался на длину
3. Отображение зп от..до с разрядами
4. Вынес форматирование зп в отдельный класс /util/Formatter.php
=> Мелкие доработки фичи Search

app/src/main/java/ru/practicum/android/diploma/favorites/presentation/view/FavoriteAdapter.kt, app/src/main/java/ru/practicum/android/diploma/search/data/HhQueryOptions.kt, app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancySearchResponse.kt, app/src/main/java/ru/practicum/android/diploma/search/data/network/RetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/impl/SearchInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/VacancySearchViewHolder.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt, app/src/main/res/values/strings.xml
Накладывалось название вакансии - ищу повар а потом разработчик и у меня повар разработчик
=> Небольшие фиксы серча

app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancySearchResponse.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt, app/src/main/res/drawable/color_cursor.xml, app/src/main/res/drawable/edit_text_background.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles.xml
- добавлена кнопка Сросить текст в строку поиска
- исправлен цвет курсора
=> Task98 search UI

app/src/main/java/ru/practicum/android/diploma/vacancydetails/data/dto/DetailsDto.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/data/dto/DetailsRequest.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/data/dto/DetailsResponse.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/data/network/HhApiServiceDetails.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/data/network/RetrofitNetworkClientDetails.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/data/repo/DetailsRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/domain/DetailsResult.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/domain/api/DetailsInteractor.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/domain/api/DetailsRepository.kt
Подготовка data и domain слоев
=> Создал дата-класс детального описания вакансии.

app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
=> hotfix-favourites: fixed di

app/src/main/java/ru/practicum/android/diploma/search/presentation/models/SearchState.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt, app/src/main/res/layout/activity_root.xml, app/src/main/res/layout/fragment_search.xml
Обернул acitivty_root в Coordinator_Layout > ConstraintLayout
иначе список вакансий (весь фрагмент контейнер) залазил под боттомнав
про пагинацию долго рассказывать, смотрите коммиты )
=> Пагинация + верстка root + фикс количества найденных вакансий

app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt, app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/data/dto/DetailsResponse.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/data/network/RetrofitNetworkClientDetails.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/domain/DetailsNotFoundType.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/domain/impl/DetailsInteractorImpl.kt
Исправления в слое Data фичи Details 
Прописал DI
=> Исправления в Details - Data + DI

app/src/main/java/ru/practicum/android/diploma/favorites/presentation/view/FavoriteViewHolder.kt
bug fix FavoriteViewHolder.kt, изменил отображение названия вакансии
=> bug fix FavoriteViewHolder.kt, изменил отображение названия вакансии

app/src/main/res/layout/fragment_favorite.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/fragment_team.xml
изменил положение названий экранов
=> изменил положение названий экранов

app/src/main/java/ru/practicum/android/diploma/search/data/network/RetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt, app/src/main/res/layout/fragment_search.xml, app/src/main/res/values/strings.xml
- в plurals была ошибка few это ваканси**и** (например 33 вакансии)
- исправил верстку теперь картинка и сообщение об ошибке друг под другом посредине экрана
- согласно макету сделал плашку с кол-вом вакансий прикрученной поверх списка вакансий (элемент списка виден из-под плашки)
- добавил ограничение страницы, теперь подгрузить новые вакансии списка прокруткой до конца можно только в пределах выборки
- bonus: этого не было в макетах, но у меня выскакивает короткий тост "Вы достигли конца списка" при попытке скроллить дальше
=> Исправлено

app/src/main/AndroidManifest.xml, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt, app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/item_vacancy_view.xml
- мелочи по верстке
- Bugfix: добавила проверку на hasFocus, чтобы отправка запроса не срабатывала при переключении фрагментов
- добавила debounce на клик в адаптере
- добавила отправку запроса на кнопку клавиатуры ОК для ручного запуска после ошибки
=> debounce на адаптере, hasFocus(), SearchByClick

app/src/main/AndroidManifest.xml, app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/sharingandcontactvacancy/data/ExternalNavigatorImpl.kt, app/src/main/java/ru/practicum/android/diploma/sharingandcontactvacancy/domain/api/ExternalNavigator.kt, app/src/main/java/ru/practicum/android/diploma/sharingandcontactvacancy/domain/api/SharingContactInteractor.kt, app/src/main/java/ru/practicum/android/diploma/sharingandcontactvacancy/domain/impl/SharingContactInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/data/dto/VacancyDetailsResponse.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/data/repo/DetailsRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/presentation/view/VacancyDetailsFragment.kt, app/src/main/res/layout/item_vacancy_details_view.xml, app/src/main/res/values/strings.xml
- добавлена новая фича sharingandcontactvacancy, слои domain, data, DI
- исправлен мелкий баг в ContactsDTO phone -> phones
- добавлены тестовые данные для контактов
=> DI Interactor Navigator для шаринга, тестовые данные для контактов

app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt, app/src/main/java/ru/practicum/android/diploma/favorites/data/converters/VacancyDbConverter.kt, app/src/main/java/ru/practicum/android/diploma/favorites/data/db/VacancyDao.kt, app/src/main/java/ru/practicum/android/diploma/favorites/data/impl/FavouriteVacancyRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/favorites/domain/db/FavouriteVacancyInteractor.kt, app/src/main/java/ru/practicum/android/diploma/favorites/domain/db/FavouriteVacancyRepository.kt, app/src/main/java/ru/practicum/android/diploma/favorites/domain/impl/FavouriteVacancyInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/presentation/models/DetailsState.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/presentation/view/VacancyDetailsFragment.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/presentation/viewmodel/DetailsViewModel.kt
=> task-141: added like and dislike button

app/src/main/java/ru/practicum/android/diploma/favorites/data/impl/FavouriteVacancyRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/models/SearchState.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/SearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/view/VacancySearchViewHolder.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/presentation/viewmodel/DetailsViewModel.kt, app/src/main/res/values/strings.xml
Постраничка все делала странным. Переписал сразу как надо было - все проверки в модели и список вакансий всегда лежит там. Иначе были глюки при переходе между фрагментами менялся и список вакансий, когда было уже больше одной страницы
=> Переписал поиск на стейты

app/src/main/java/ru/practicum/android/diploma/favorites/presentation/view/FavoriteFragment.kt
=> Task 163 fav bug

app/src/main/java/ru/practicum/android/diploma/favorites/data/impl/FavouriteVacancyRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/favorites/domain/db/FavouriteVacancyInteractor.kt, app/src/main/java/ru/practicum/android/diploma/favorites/domain/db/FavouriteVacancyRepository.kt, app/src/main/java/ru/practicum/android/diploma/favorites/domain/impl/FavouriteVacancyInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/favorites/presentation/view/FavoriteFragment.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/presentation/view/VacancyDetailsFragment.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/presentation/viewmodel/DetailsViewModel.kt
added internet check, get vacancy from database
=> task-connection-details

app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt
проверяю интернет, прежде чем вычислять что страница последняя на основе page/pages
=> проверяю интернет, прежде чем вычислять что страница последняя

app/src/main/java/ru/practicum/android/diploma/vacancydetails/presentation/view/VacancyDetailsFragment.kt, app/src/main/res/drawable/arrow_back_24px.xml, app/src/main/res/drawable/bottom_nav_background.xml, app/src/main/res/drawable/favorites_off_24px_button.xml, app/src/main/res/layout/activity_root.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/fragment_vacancy_details.xml, app/src/main/res/layout/item_vacancy_details_view.xml, app/src/main/res/values-night/colors.xml, app/src/main/res/values-night/styles.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
-  ЗП не показывается на VacancyDetailsFragment
-  Заголовок и Fav не видно в темной теме
-  на темной теме цвет в плашке название компании, город должен оставаться черным
-  цвет системного бара как на макетах
-  заголовки в вакансии как на макетах
-  в темной теме отображается разделитель bottomNav и экрана (точнее линия отображается на всех экранах, а должна только там где виден bottomNav)
-  маленькое расстояние между плашкой общего количества вакансий и списка с вакансиями (отступ отсутствует, нужен порядка 4dp, если от самого текста, то где-то 8dp)
=> закрываем чеки по задаче

app/src/main/java/ru/practicum/android/diploma/search/presentation/view/VacancySearchViewHolder.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/presentation/view/VacancyDetailsFragment.kt
чтобы лого компаний без инета не показывались
=> отключил кэш Glide

app/src/main/java/ru/practicum/android/diploma/util/Formatter.kt, app/src/main/res/values/strings.xml
=> Добавил вариант от 100 000 р до 100 000 р

app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt, app/src/main/java/ru/practicum/android/diploma/di/DiConstants.kt, app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/dto/AreasCatalogDto.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/dto/AreasCatalogResponse.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/network/AreaRetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/network/AreasRetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/network/HhApiServiceArea.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/network/HhApiServiceAreas.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/domain/models/AreasNotFoundType.kt
- Network и Dto для запроса Areas
- DI обновлен, в DI внесены правки по ревью
=> Task197 choose area

app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/dto/AreasCatalogDto.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/dto/AreasCatalogRequest.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/dto/AreasRequest.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/dto/CountriesRequest.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/network/AreasRetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/network/HhApiServiceAreas.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/repo/ChooseAreaRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/domain/api/ChooseAreaInteractor.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/domain/api/ChooseAreaRepository.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/domain/impl/ChooseAreaInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/domain/models/AreaInfo.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/domain/models/AreasResult.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/domain/models/CountriesResult.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/domain/models/CountryInfo.kt
- ChooseAreaInteractor and Impl
- ChooseAreaRepository and Impl
- DI update
=> Task197 repo domain

app/src/main/res/drawable/background_blue_rounded.xml, app/src/main/res/layout/fragment_chooosing_region.xml, app/src/main/res/layout/fragment_choosing_country.xml, app/src/main/res/layout/fragment_choosing_place_work.xml, app/src/main/res/layout/item_choosing_area_country.xml, app/src/main/res/values/styles.xml
Сверстал экраны:
1. Выбора места работы
2. Выбор страны
3. Выбор региона 
4. Кастомизировал стиль синей кнопки "Выбрать"
=> Верстка экранов "Выбор места работы", "Выбор страны", "Выбор региона" 

app/src/main/java/ru/practicum/android/diploma/root/ui/RootActivity.kt, app/src/main/res/layout/fragment_choosing_industry.xml, app/src/main/res/layout/item_choosing_industry.xml, app/src/main/res/navigation/nav_graph.xml
Сверстал экран "Выбор отрасли"
Убрал bottomNav на экранах фильтрации
Поставил обложки в графе навигации
=> Верстка экрана "Выбор отрасли"

app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt, app/src/main/java/ru/practicum/android/diploma/di/DiConstants.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/repo/ChooseAreaRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/storage/AreasStorageApi.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/storage/AreasStorageImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/domain/api/ChooseAreaInteractor.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/domain/api/ChooseAreaRepository.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/domain/impl/ChooseAreaInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/presentation/viewmodel/ChooseAreaViewModel.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/presentation/viewmodel/ChooseCountryViewModel.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/ui/ChooseAreaFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/ui/ChooseCountryFragment.kt, app/src/main/res/layout/fragment_chooosing_region.xml, app/src/main/res/layout/fragment_choosing_place_work.xml
- добавление страны
- удаление страны
- сохранение настроек страны на экране Выбор места работы
- префы для Countries 
- префы для всего проекта -DI
=> Task194 countries share prefs

app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/network/AreasRetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/search/data/HhQueryOptions.kt, app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancySearchRequestDto.kt, app/src/main/java/ru/practicum/android/diploma/search/data/network/RetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/search/data/repo/SearchRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/api/SearchInteractor.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/api/SearchRepository.kt, app/src/main/java/ru/practicum/android/diploma/search/domain/impl/SearchInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt, app/src/main/res/layout/fragment_filters_settings.xml, app/src/main/res/values/strings.xml
- настроил функцию поиска на VacancySearchRequest - прокинул в репозиторий параметры зарплаты из настроек (параметры региона пока не делал)
- hotfix HttpException из правильного пакета
- hotfix уникальные вакансии проверяем не по сочетанию названия/компании/... а по hhID (такие дубли поиск тоже выдает)
=> Внедрение фильтров в Search

app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/presentation/viewmodel/SettingsFiltersViewModel.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/ui/SettingsFiltersFragment.kt
=> Чекбокс "не показывать без зарплаты"

app/src/main/java/ru/practicum/android/diploma/common/presentation/Currency.kt, app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt, app/src/main/java/ru/practicum/android/diploma/favorites/data/converters/VacancyDbConverter.kt, app/src/main/java/ru/practicum/android/diploma/favorites/data/impl/FavouriteVacancyRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/storage/AreasStorageImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/data/storage/SettingsStorageImpl.kt, app/src/main/java/ru/practicum/android/diploma/util/Formatter.kt
=> Исправление замечаний ревьюера к итерации 2

app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/data/dto/IndustryDto.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/data/network/HhApiServiceIndustry.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/data/network/IndustryRetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/data/repo/IndustryRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/presentation/models/IndustriesStates.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/presentation/viewmodel/ChooseIndustryViewModel.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/ui/ChooseIndustryAdapter.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/ui/ChooseIndustryFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/ui/ChooseIndustryViewHolder.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/ui/SettingsFiltersFragment.kt, app/src/main/res/layout/fragment_filters_settings.xml
=> Task 196 view

app/src/main/java/ru/practicum/android/diploma/filters/choosearea/presentation/viewmodel/ChooseAreaViewModel.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/ui/ChooseAreaFragment.kt, app/src/main/res/drawable/clear_24px_input_edittext_button.xml, app/src/main/res/layout/fragment_choosing_place_work.xml, app/src/main/res/layout/item_choosing_region_country.xml
Исправил отображение кнопки очистить в темной теме.
Изменил отображение полей Страна и Регион
=> Task 224 place work hotfix

app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt, app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt, app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/ui/ChooseAreaFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/ui/ChooseCountryFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/ui/ChooseRegionFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/data/repo/IndustryRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/data/storage/IndustryStorageApi.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/data/storage/IndustryStorageImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/domain/impl/IndustryInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/domain/interfaces/IndustryInteractor.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/domain/interfaces/IndustryRepository.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/presentation/viewmodel/ChooseIndustryViewModel.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/ui/ChooseIndustryAdapter.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/ui/ChooseIndustryFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/ui/ChooseIndustryViewHolder.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/presentation/viewmodel/SettingsFiltersViewModel.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/ui/SettingsFiltersFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt
1. Добавление отображения отрасли на главный экран фильтров.
2. Сохранение Отрасли
3. Обработка нажатия на экране Отрасли, можно выбрать только одну отрасль и подтвердить выбор кнопкой
4. Сохранение значения поля ввода на экране Настройки фильтров
5. Переходы по кнопке "назад" на предыдущие экраны
=> 1. Добавление отображения отрасли на главный экран фильтров.

app/src/main/java/ru/practicum/android/diploma/filters/choosearea/ui/ChooseAreaFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/ui/ChooseCountryFragment.kt
Добавил обработку кнопки назад в "Выбор места работы"
Обработка ошибок на экране "Выбор страны"
=> Task 198 place work corrections

app/src/main/java/ru/practicum/android/diploma/common/domain/FiltersAll.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/data/repo/SettingsRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/data/storage/SettingsStorageApi.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/data/storage/SettingsStorageImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/domain/api/SettingsInteractor.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/domain/api/SettingsRepository.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/domain/impl/SettingsInteractorImpl.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/presentation/viewmodel/SettingsFiltersViewModel.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/ui/SettingsFiltersFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
применяются предыдущие фильтры
вплоть до того момента как..
- не применишь фильтры кнопкой применить
- не сотрешь поисковую строку (текущий фильтр применится к новому поиску)
назвал stashedFilters (припрятанные фильтры) и организовал хранение в pref
=> При выходе с настроек фильтра по кнопке назад

app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/ui/SettingsFiltersFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/data/network/RetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
попробуем победить баг, когда идешь в фильтр ставишь страну применить, ищешь "водитель", идешь в фильтр ставишь зп, жмешь назад и видишь пустой поиск по слову водитель
=> Hotfix 2307

app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/ui/SettingsFiltersFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
Исправлено: показывались результаты поиска если
ввести маску, перейти в фильтры, применить фильтры, стереть поиск крестиком, перейти в фильтры, нажать назад
Исправлено: при выборе только страны без региона кнопка фильтра не выделялась
=> правим баги

app/src/main/java/ru/practicum/android/diploma/filters/choosearea/data/network/AreasRetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/ui/ChooseAreaFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/choosearea/ui/ChooseRegionFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/data/network/IndustryRetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/filters/chooseindustry/ui/ChooseIndustryFragment.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/ui/SettingsFiltersBinding.kt, app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/ui/SettingsFiltersFragment.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/ui/VacancyDetailsFragment.kt
=> Iteration 3 review

app/src/main/java/ru/practicum/android/diploma/filters/settingsfilters/ui/SettingsFiltersFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/data/network/RetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
очевидно проблема была в безусловном сохранении фильтра на нажатие кнопки назад
добавил условие на непустой поиск
=> Task 290 (баг с кнопкой применить)

app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
=> Task 279 (мигает прогресс бар без интернета)

app/src/main/java/ru/practicum/android/diploma/filters/choosearea/ui/ChooseAreaFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancySearchDto.kt, app/src/main/java/ru/practicum/android/diploma/search/data/network/RetrofitNetworkClient.kt, app/src/main/java/ru/practicum/android/diploma/search/data/repo/SearchRepositoryImpl.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt, app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragmentHelper.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/data/network/RetrofitNetworkClientDetails.kt, app/src/main/java/ru/practicum/android/diploma/vacancydetails/data/repo/DetailsRepositoryImpl.kt
Эти ошибки вылезут на итерации
=> Predetekt fix
